# Data Preprocessing Tools

## Importing the libraries

Importar las librerias:



```
numpy: llamela np
matplotlib.pyplot: llamela plt
pandas: llamela pd

```



In [1]:
"""Escribe tu codigo aquí"""
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset



```
Utilice pandas para leer el csv (read_csv), guardelo en una variable llamado dataset. 

El objetivo es luego de leer el dataset construir 1 matriz que contiene los features (3 primeras columnas), y un vector que es el que tiene la variable dependiente. 

Nombrelas como X e y respectivamente. 

Recuerde que pandas trabaja con dataframes, puede usar la funcion iloc[i,i] que recibe 2 indices, el primero son las filas y el segundo las columnas y que con el operador : puede decirle quiero todos los valores hasta el final.


```




In [8]:
"""Escribe tu codigo aquí"""

'Escribe tu codigo aquí'

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data


```
Por primera vez, vamos a utilizar sckit-learn para manejar datos faltantes, en particular importaremos SimpleImputer 

cree una variable llamada imputer y aplique la funcion previamente Importada pasandole como parametro missing_values = np.nan y strategy = 'defina usted la estrategia' 

Detengase a pensar un segundo para elegir la mejor estrategia. 

Luego aplique al imputer (objeto de entrada) con el metodo fit a la matriz de caracteristicas X[i,i] indicandole los indices como lo hizo al principio, es decir a que columnas quiere aplicarle la estrategia de completado de datos

Finalmente con el metodo transform sobre el imputer aplicaremos a la matriz de caracteristicas y le asignaremos a la misma matriz de caracteristicas para que quede remplazado el valor y de ahi en mas usemos esa.

```



In [21]:
from sklearn.impute import SimpleImputer
"""Escribe tu codigo aquí"""

'Escribe tu codigo aquí'

In [20]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

Usaremos One Hot Encoding para transformar las columnas categoricas a vector binario para que el modelo pueda interpretarlas. 

En la siguiente celda quisieramos aplicar al ct el metodo fit_transform sobre nuestra matriz de caracteristicas de modo que los paises sean transformados. 

Ademas queremos que la salida sea un numpy array.. para eso le aplicaremos np.array a lo anterior y lo guardaremos en una variable llamada X para seguir usando nuestra Matriz con la codificación

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
"""Escribe tu codigo aquií"""

'Escribe tu codigo aquií'

In [23]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable



```
Utilice la clase LabelEncoder 

asigne a una variable llamada le el metodo LabelEncoder()  y luego apliquele el método fit_transform a nuestra variable dependiente

```





In [27]:
"""Escribe tu código aquí"""

'Escribe tu código aquí'

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set


```
Partiremos nuetro dataset en training 80% y test set 20%

para eso usaremos `train_test_split` y le asignaremos a: X_train, X_test, y_train, y_test el resultado de aplicar le `train_test_split` y le pasaremos nuestra matriz X, nuetra matriz y,  el test_size = 0.2 y random_state = 1 para a todos nos muestre el mismo resultado

NOTA: Se puede cambiar la semilla del random para que divida el dataset de manera  aleatoria.

```



In [31]:
from sklearn.model_selection import train_test_split
"""Escribe tu código aquí"""

'Escribe tu código aquí'

In [30]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

Necesitamos escalar algunos features para que no dominen en el entrenamiento sobre otros


Existen varias tecnicas, vamos a aplicar StandarScaler que consiste en:

X_stand = x - mean(x) / std(x)

Normalization sirve cuando la mayoria de tus features tienen una distribucion normal. 

X_norm = x - min(x) / max(x) - min(x)

NOTA: La estandarizacion funciona siempre, la normalización en algunos casos. 



```
pasos a seguir: 

Guardaremos en una variable llamada sc la clase StandarScaler() 

y se lo aplicaremos a la o las columnas que creamos que debemos estandarizar

Para ello es necesario aplicar el metodo fit_transform sobre la matriz X_train por un lado y sobre la matriz X_test por otro lado

```




In [32]:
from sklearn.preprocessing import StandardScaler
"""Escribe tu código aquí"""

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
